name: streamlit application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn matplotlib seaborn streamlit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check docker image build status
      run: |
        docker build -f Dockerfile -t stepstoneapp:latest
